const sampleData = [
  {
    product_id: 1,
    product_name: "product1",
    price: 100,
    record_count: 5250,
    category: "furniture",
  },
  {
    product_id: 2,
    product_name: "oinkoink",
    price: 200,
    record_count: 520,
    category: "books",
  },
  {
    product_id: 3,
    product_name: "product3",
    price: 300,
    record_count: 250,
    category: "clothing",
  },
  {
    product_id: 4,
    product_name: "sliced",
    price: 150,
    record_count: 1240,
    category: "toys",
  },
  {
    product_id: 5,
    product_name: "zinger",
    price: 250,
    record_count: 1430,
    category: "sports",
  },
  {
    product_id: 6,
    product_name: "mango",
    price: 50,
    record_count: 8300,
    category: "electronics",
  },
  {
    product_id: 7,
    product_name: "queen",
    price: 180,
    record_count: 430,
    category: "furniture",
  },
  {
    product_id: 8,
    product_name: "product8",
    price: 130,
    record_count: 7800,
    category: "home & kitchen",
  },
  {
    product_id: 9,
    product_name: "product9",
    price: 220,
    record_count: 1150,
    category: "books",
  },
  {
    product_id: 10,
    product_name: "product10",
    price: 160,
    record_count: 320,
    category: "clothing",
  },
  {
    product_id: 11,
    product_name: "product11",
    price: 90,
    record_count: 6200,
    category: "sports",
  },
  {
    product_id: 12,
    product_name: "product12",
    price: 270,
    record_count: 400,
    category: "toys",
  },
  {
    product_id: 13,
    product_name: "product13",
    price: 200,
    record_count: 670,
    category: "home & kitchen",
  },
  {
    product_id: 14,
    product_name: "monitor",
    price: 300,
    record_count: 210,
    category: "electronics",
  },
  {
    product_id: 15,
    product_name: "apple",
    price: 180,
    record_count: 900,
    category: "furniture",
  },
];
export default sampleData;
